name = "gomoku-api"
pages_build_output_dir = "./pages_build"
compatibility_date = "2024-09-03"

[[d1_databases]]
binding = "DB"
database_name = "gomoku-db"
database_id = "4cd53ea1-ef41-450e-843c-b48f6121cf7c"

[[durable_objects.bindings]]
name = "GOMOKU_ROOMS"
class_name = "GomokuRoom"
script_name = "gomoku-backend"

[[durable_objects.bindings]]
name = "GOMOKU_SOCIAL"
class_name = "SocialHub"
script_name = "gomoku-backend"
